
- name: install basic packages
  become: true
  apt: name={{item}} state=present
  with_items:
       - curl
       - git
       - vim   
       - zsh
       - terminator
       - apt-transport-https
       - ca-certificates
